[package]
name = "lusid-ssh"
version = "0.1.0"
edition = "2024"

[dependencies]
lusid-fs = { path = "../fs", version = "0.1" }
async-promise = "0.1.1"
base64ct = "1.8.3"
bytes = "1"
futures-util = "0.3.32"
russh.workspace = true
russh-sftp = "2.1.2"
thiserror.workspace = true
termion = "4.0.6"
tokio.workspace = true
tracing.workspace = true
signal-hook = "0.3.18"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["macros", "rt"] }
