[package]
name = "lusid-apply-stdio"
version = "0.2.0"
edition = "2024"

[dependencies]
lusid-operation = { path = "../operation", version = "0.2" }
lusid-plan = { path = "../plan", version = "0.2" }
lusid-resource = { path = "../resource", version = "0.2" }
lusid-tree = { path = "../tree", version = "0.2" }
base64.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
