[package]
name = "lusid-render"
version = "0.2.0"
edition = "2024"

[dependencies]
lusid-operation = { path = "../operation", version = "0.2" }
lusid-plan = { path = "../plan", version = "0.2" }
lusid-resource = { path = "../resource", version = "0.2" }
ratatui = "0.30"
similar = { version = "2", default-features = false, features = ["text"] }
termtree = "1.0.0"
