[package]
name = "lusid"
version = "0.1.0"
edition = "2024"

[dependencies]
lusid-apply-stdio = { path = "../apply-stdio", version = "0.1" }
lusid-cmd = { path = "../cmd", version = "0.1" }
lusid-ctx = { path = "../ctx", version = "0.1" }
lusid-machine = { path = "../machine", version = "0.1" }
lusid-params = { path = "../params", version = "0.1" }
lusid-plan = { path = "../plan", version = "0.1" }
lusid-render = { path = "../render", version = "0.1" }
lusid-secrets = { path = "../secrets", version = "0.1" }
lusid-ssh = { path = "../ssh", version = "0.1" }
lusid-store = { path = "../store", version = "0.1" }
lusid-system = { path = "../system", version = "0.1" }
lusid-vm = { path = "../vm", version = "0.1" }
comfy-table = "7.2.2"
clap.workspace = true
crossterm = "0.29"
displaydoc.workspace = true
ratatui = "0.30"
rimu.workspace = true
rimu-interop = { path = "../rimu-interop", version = "0.1" }
serde.workspace = true
serde_json.workspace = true
shell-words = "1.1.1"
thiserror.workspace = true
tokio.workspace = true
toml = "1.1.2"
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
